CREATE TABLE IF NOT EXISTS books (
	id            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title         TEXT NOT NULL,
	description   TEXT,
	isbn          TEXT NOT NULL UNIQUE,
	numOfPages    INTEGER DEFAULT 0,
	rating        INTEGER DEFAULT 0,
	state         TEXT NOT NULL DEFAULT "unread",
	dateAdded     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	dateUpdated   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	dateCompleted TIMESTAMP
);

-- create state enum

CREATE TABLE IF NOT EXISTS authors (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books_authors (
	book_id INTEGER REFERENCES books(id),
	author_id INTEGER REFERENCES authors(id),
	PRIMARY KEY(book_id, author_id)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	username VARCHAR(255) NOT NULL UNIQUE,
	hashed_password CHAR(60) NOT NULL,
	role TEXT NOT NULL DEFAULT "user",
	dateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create role enum

CREATE TABLE IF NOT EXISTS apikeys (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	userId INTEGER NOT NULL,
	hashed_key TEXT NOT NULL UNIQUE,
	dateAdded TIMESTAMP NOT NULL,
	dateExpired TIMESTAMP NOT NULL
);

