//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Books struct {
	ID            *int32 `sql:"primary_key"`
	Title         string
	Description   *string
	Isbn          string
	NumOfPages    *int32
	Rating        *int32
	State         string
	DateAdded     *int32
	DateUpdated   *int32
	DateCompleted *int32
}
