name: Run tests
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Verify dependencies
        run: go mod verify

      - name: Build application
        run: make build

      - name: Run tests
        run: go test -race ./...

  # dockerize:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v2
  #
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: '1.18'
  #
  #     - name: Build application
  #       run: go build ./...
  #
  #     - name: Build Docker image
